// ---------------------------------------------------------------------------
// APT Attack Chains
// ---------------------------------------------------------------------------
// Each attack chain models the step-by-step progression of a specific APT
// group through an intrusion, mapped to MITRE ATT&CK tactics and techniques.
// Chains include suggested Net-Runner tools and specialist agents for each
// phase, enabling the LLM to simulate the attack pattern autonomously.
//
// These chains are curated from public threat intelligence — MITRE ATT&CK
// group pages, CISA advisories, and vendor reports cited in aptGroups.ts.
// ---------------------------------------------------------------------------

import type { AptAttackChain } from './types.js'

// ═══════════════════════════════════════════════════════════════════════════
// GOVERNMENT / ESPIONAGE CHAINS
// ═══════════════════════════════════════════════════════════════════════════

export const APT29_GOV_CHAIN: AptAttackChain = {
  aptGroupId: 'apt29',
  name: 'APT29 — Government Cloud Espionage',
  description:
    'Models APT29\'s modern tradecraft: cloud-focused initial access via credential theft or OAuth abuse, lateral movement through cloud services, and exfiltration of email and documents from M365/cloud storage. Reflects the CISA 2024 SVR cloud-access advisory.',
  relevantIndustries: ['government', 'technology', 'healthcare'],
  recommendedImpact: 'intrusive',
  phases: [
    {
      order: 1,
      tacticId: 'TA0043',
      label: 'Reconnaissance',
      description: 'Identify target personnel, email addresses, cloud tenant details, and public-facing services. Focus on IT administrators and cloud infrastructure.',
      techniques: ['T1589.002', 'T1591', 'T1593', 'T1594'],
      suggestedTools: ['theHarvester', 'subfinder', 'amass', 'holehe', 'GHunt'],
      suggestedAgents: ['recon-specialist'],
    },
    {
      order: 2,
      tacticId: 'TA0042',
      label: 'Resource Development',
      description: 'Prepare credential-harvesting infrastructure, phishing domains, and OAuth application registrations.',
      techniques: ['T1583.001', 'T1583.006', 'T1585', 'T1588.002'],
      suggestedTools: ['gophish'],
      suggestedAgents: ['engagement-lead'],
    },
    {
      order: 3,
      tacticId: 'TA0001',
      label: 'Initial Access',
      description: 'Deliver spearphishing links to credential-harvesting pages targeting cloud SSO. Alternatively, abuse valid cloud credentials obtained through password spraying or token theft.',
      techniques: ['T1566.002', 'T1078.004', 'T1195.002'],
      suggestedTools: ['gophish', 'nuclei', 'httpx'],
      suggestedAgents: ['web-testing-specialist', 'exploit-specialist'],
    },
    {
      order: 4,
      tacticId: 'TA0002',
      label: 'Execution',
      description: 'Execute commands via cloud management APIs, PowerShell, or remote management tools.',
      techniques: ['T1059.001', 'T1059.003'],
      suggestedTools: ['crackmapexec', 'evil-winrm'],
      suggestedAgents: ['exploit-specialist'],
    },
    {
      order: 5,
      tacticId: 'TA0003',
      label: 'Persistence',
      description: 'Create additional cloud credentials, register OAuth applications, or add cloud accounts for persistent access.',
      techniques: ['T1098.001', 'T1136.003', 'T1078.004'],
      suggestedTools: ['evil-winrm', 'crackmapexec'],
      suggestedAgents: ['privilege-escalation-specialist'],
    },
    {
      order: 6,
      tacticId: 'TA0005',
      label: 'Defense Evasion',
      description: 'Use stolen tokens to bypass MFA, disable security logging, and blend into legitimate admin activity.',
      techniques: ['T1550.001', 'T1562.001', 'T1070.004'],
      suggestedTools: [],
      suggestedAgents: ['exploit-specialist'],
    },
    {
      order: 7,
      tacticId: 'TA0006',
      label: 'Credential Access',
      description: 'Harvest OAuth tokens, steal application access tokens, extract credentials from cloud vaults, and conduct password spraying.',
      techniques: ['T1528', 'T1539', 'T1110.003', 'T1621'],
      suggestedTools: ['crackmapexec', 'hydra'],
      suggestedAgents: ['privilege-escalation-specialist'],
    },
    {
      order: 8,
      tacticId: 'TA0007',
      label: 'Discovery',
      description: 'Enumerate cloud infrastructure, tenant configurations, privileged accounts, and connected services.',
      techniques: ['T1087.002', 'T1069.002', 'T1580', 'T1082'],
      suggestedTools: ['bloodhound', 'ldapsearch'],
      suggestedAgents: ['recon-specialist', 'ad-specialist'],
    },
    {
      order: 9,
      tacticId: 'TA0008',
      label: 'Lateral Movement',
      description: 'Move between cloud tenants, on-prem to cloud, and across federated identity boundaries using stolen tokens and pass-the-hash.',
      techniques: ['T1550.002', 'T1021.001', 'T1021.006'],
      suggestedTools: ['evil-winrm', 'crackmapexec', 'impacket'],
      suggestedAgents: ['lateral-movement-specialist'],
    },
    {
      order: 10,
      tacticId: 'TA0009',
      label: 'Collection',
      description: 'Access email via Graph API, download documents from SharePoint/OneDrive, and collect data from cloud storage.',
      techniques: ['T1114.002', 'T1530', 'T1005', 'T1560.001'],
      suggestedTools: [],
      suggestedAgents: ['evidence-specialist'],
    },
    {
      order: 11,
      tacticId: 'TA0010',
      label: 'Exfiltration',
      description: 'Exfiltrate collected data over encrypted HTTPS channels or to attacker-controlled cloud storage.',
      techniques: ['T1041', 'T1567.002'],
      suggestedTools: [],
      suggestedAgents: ['evidence-specialist', 'reporting-specialist'],
    },
  ],
}

export const APT28_GOV_CHAIN: AptAttackChain = {
  aptGroupId: 'apt28',
  name: 'APT28 — Government Credential Harvesting & Espionage',
  description:
    'Models APT28\'s aggressive credential-harvesting approach: zero-day exploitation, credential phishing, and broad lateral movement through Windows AD environments. Reflects GRU Unit 26165 tradecraft.',
  relevantIndustries: ['government', 'defense', 'energy'],
  recommendedImpact: 'intrusive',
  phases: [
    {
      order: 1,
      tacticId: 'TA0043',
      label: 'Reconnaissance',
      description: 'Map target organization structure, identify key personnel, harvest email addresses, and discover public-facing infrastructure.',
      techniques: ['T1589.002', 'T1590', 'T1593', 'T1596'],
      suggestedTools: ['theHarvester', 'subfinder', 'amass', 'shodan'],
      suggestedAgents: ['recon-specialist'],
    },
    {
      order: 2,
      tacticId: 'TA0001',
      label: 'Initial Access',
      description: 'Deliver spearphishing attachments with exploits or links to credential-harvesting sites. Exploit public-facing email/VPN appliances when zero-days are available.',
      techniques: ['T1566.001', 'T1566.002', 'T1190', 'T1133'],
      suggestedTools: ['gophish', 'nuclei', 'httpx'],
      suggestedAgents: ['web-testing-specialist', 'exploit-specialist'],
    },
    {
      order: 3,
      tacticId: 'TA0002',
      label: 'Execution',
      description: 'Execute payloads via macro-enabled documents, PowerShell, and exploitation of client applications.',
      techniques: ['T1059.001', 'T1059.003', 'T1059.005', 'T1204.002', 'T1203'],
      suggestedTools: ['crackmapexec', 'evil-winrm'],
      suggestedAgents: ['exploit-specialist'],
    },
    {
      order: 4,
      tacticId: 'TA0003',
      label: 'Persistence',
      description: 'Install registry run keys, create Windows services, and establish scheduled tasks for persistent callback.',
      techniques: ['T1547.001', 'T1053.005', 'T1543.003'],
      suggestedTools: ['crackmapexec'],
      suggestedAgents: ['privilege-escalation-specialist'],
    },
    {
      order: 5,
      tacticId: 'TA0004',
      label: 'Privilege Escalation',
      description: 'Exploit local vulnerabilities or use process injection to escalate to SYSTEM. Abuse DLL search-order hijacking.',
      techniques: ['T1068', 'T1055', 'T1574.001'],
      suggestedTools: ['crackmapexec', 'evil-winrm'],
      suggestedAgents: ['privilege-escalation-specialist'],
    },
    {
      order: 6,
      tacticId: 'TA0006',
      label: 'Credential Access',
      description: 'Dump LSASS memory, conduct password spraying, harvest credentials from files, and intercept authentication.',
      techniques: ['T1003.001', 'T1110.001', 'T1110.003', 'T1552.001', 'T1557'],
      suggestedTools: ['crackmapexec', 'mimikatz', 'hydra', 'responder'],
      suggestedAgents: ['privilege-escalation-specialist', 'ad-specialist'],
    },
    {
      order: 7,
      tacticId: 'TA0007',
      label: 'Discovery',
      description: 'Enumerate AD structure, domain trusts, network shares, and connected systems.',
      techniques: ['T1087.002', 'T1082', 'T1083', 'T1016', 'T1049'],
      suggestedTools: ['bloodhound', 'ldapsearch', 'nmap', 'enum4linux'],
      suggestedAgents: ['recon-specialist', 'ad-specialist'],
    },
    {
      order: 8,
      tacticId: 'TA0008',
      label: 'Lateral Movement',
      description: 'Move through the network using RDP, SMB, pass-the-hash, and lateral tool transfer.',
      techniques: ['T1021.001', 'T1021.002', 'T1550.002', 'T1570'],
      suggestedTools: ['crackmapexec', 'impacket', 'evil-winrm'],
      suggestedAgents: ['lateral-movement-specialist'],
    },
    {
      order: 9,
      tacticId: 'TA0009',
      label: 'Collection',
      description: 'Collect email archives, documents from file shares, and capture keystrokes and screenshots.',
      techniques: ['T1560.001', 'T1005', 'T1039', 'T1114.002', 'T1056.001', 'T1113'],
      suggestedTools: [],
      suggestedAgents: ['evidence-specialist'],
    },
    {
      order: 10,
      tacticId: 'TA0011',
      label: 'Command and Control',
      description: 'Maintain C2 over HTTPS with encrypted channels and proxy infrastructure.',
      techniques: ['T1071.001', 'T1573.001', 'T1090.002', 'T1105'],
      suggestedTools: [],
      suggestedAgents: ['network-testing-specialist'],
    },
    {
      order: 11,
      tacticId: 'TA0010',
      label: 'Exfiltration',
      description: 'Exfiltrate archived data over C2 channel or alternative protocols.',
      techniques: ['T1041', 'T1048'],
      suggestedTools: [],
      suggestedAgents: ['evidence-specialist', 'reporting-specialist'],
    },
  ],
}

// ═══════════════════════════════════════════════════════════════════════════
// CRITICAL INFRASTRUCTURE / ENERGY CHAINS
// ═══════════════════════════════════════════════════════════════════════════

export const VOLT_TYPHOON_INFRA_CHAIN: AptAttackChain = {
  aptGroupId: 'volt-typhoon',
  name: 'Volt Typhoon — Critical Infrastructure Pre-Positioning',
  description:
    'Models Volt Typhoon\'s living-off-the-land approach: exploit edge devices, use only built-in OS tools, avoid malware, and establish long-term access to critical infrastructure for potential disruption. Reflects CISA/Microsoft 2024 advisories.',
  relevantIndustries: ['critical-infrastructure', 'manufacturing', 'energy', 'government'],
  recommendedImpact: 'limited',
  phases: [
    {
      order: 1,
      tacticId: 'TA0043',
      label: 'Reconnaissance',
      description: 'Identify internet-facing network appliances, VPN concentrators, and edge devices. Map the target organization\'s network perimeter.',
      techniques: ['T1595.001', 'T1595.002', 'T1590', 'T1596'],
      suggestedTools: ['nmap', 'shodan', 'subfinder', 'nuclei'],
      suggestedAgents: ['recon-specialist'],
    },
    {
      order: 2,
      tacticId: 'TA0001',
      label: 'Initial Access',
      description: 'Exploit public-facing network appliances (Fortinet, Ivanti, etc.) or abuse compromised valid credentials for VPN/remote access.',
      techniques: ['T1190', 'T1133', 'T1078'],
      suggestedTools: ['nuclei', 'httpx', 'nmap'],
      suggestedAgents: ['exploit-specialist', 'network-testing-specialist'],
    },
    {
      order: 3,
      tacticId: 'TA0002',
      label: 'Execution',
      description: 'Execute commands using only built-in OS tools — PowerShell, cmd.exe, WMI. No malware deployment.',
      techniques: ['T1059.001', 'T1059.003', 'T1047'],
      suggestedTools: ['crackmapexec', 'evil-winrm'],
      suggestedAgents: ['exploit-specialist'],
    },
    {
      order: 4,
      tacticId: 'TA0003',
      label: 'Persistence',
      description: 'Create local accounts and maintain access through valid credential reuse. Minimize forensic artifacts.',
      techniques: ['T1078', 'T1136.001'],
      suggestedTools: ['crackmapexec'],
      suggestedAgents: ['privilege-escalation-specialist'],
    },
    {
      order: 5,
      tacticId: 'TA0005',
      label: 'Defense Evasion',
      description: 'Living-off-the-land: use only signed OS binaries, clear logs, disable security tools. Avoid file drops entirely.',
      techniques: ['T1218', 'T1036', 'T1070.004', 'T1202', 'T1562.001'],
      suggestedTools: [],
      suggestedAgents: ['exploit-specialist'],
    },
    {
      order: 6,
      tacticId: 'TA0006',
      label: 'Credential Access',
      description: 'Dump credentials from LSASS, extract from credential stores, and harvest credentials from configuration files.',
      techniques: ['T1003.001', 'T1552.001', 'T1555'],
      suggestedTools: ['crackmapexec', 'mimikatz'],
      suggestedAgents: ['privilege-escalation-specialist'],
    },
    {
      order: 7,
      tacticId: 'TA0007',
      label: 'Discovery',
      description: 'Extensive internal discovery using native tools — systeminfo, ipconfig, net commands, nltest, tasklist.',
      techniques: ['T1082', 'T1083', 'T1087.002', 'T1046', 'T1135', 'T1016', 'T1049', 'T1033', 'T1007'],
      suggestedTools: ['nmap', 'enum4linux', 'ldapsearch'],
      suggestedAgents: ['recon-specialist', 'network-testing-specialist'],
    },
    {
      order: 8,
      tacticId: 'TA0008',
      label: 'Lateral Movement',
      description: 'Move laterally using RDP, SSH, and pass-the-hash with harvested credentials.',
      techniques: ['T1021.001', 'T1021.004', 'T1550.002'],
      suggestedTools: ['crackmapexec', 'impacket', 'evil-winrm'],
      suggestedAgents: ['lateral-movement-specialist'],
    },
    {
      order: 9,
      tacticId: 'TA0009',
      label: 'Collection',
      description: 'Collect network diagrams, OT documentation, configuration files, and architecture data from file shares.',
      techniques: ['T1560.001', 'T1005', 'T1039'],
      suggestedTools: [],
      suggestedAgents: ['evidence-specialist'],
    },
    {
      order: 10,
      tacticId: 'TA0011',
      label: 'Command and Control',
      description: 'Maintain low-profile C2 using protocol tunneling, proxied connections, and encrypted channels over standard ports.',
      techniques: ['T1071.001', 'T1090.002', 'T1572', 'T1105'],
      suggestedTools: [],
      suggestedAgents: ['network-testing-specialist'],
    },
    {
      order: 11,
      tacticId: 'TA0010',
      label: 'Exfiltration',
      description: 'Stage and exfiltrate collected data over the C2 channel.',
      techniques: ['T1041'],
      suggestedTools: [],
      suggestedAgents: ['evidence-specialist', 'reporting-specialist'],
    },
  ],
}

export const SANDWORM_ICS_CHAIN: AptAttackChain = {
  aptGroupId: 'sandworm',
  name: 'Sandworm — ICS/OT Destructive Operations',
  description:
    'Models Sandworm\'s destructive tradecraft against industrial control systems and critical infrastructure. Includes IT network compromise as staging, OT boundary crossing, and destructive impact operations. Based on Industroyer/CrashOverride and NotPetya campaigns.',
  relevantIndustries: ['critical-infrastructure', 'energy', 'government'],
  recommendedImpact: 'intrusive',
  phases: [
    {
      order: 1,
      tacticId: 'TA0043',
      label: 'Reconnaissance',
      description: 'Identify IT/OT boundary points, SCADA endpoints, and engineering workstations. Map the industrial network architecture from the IT side.',
      techniques: ['T1595.001', 'T1590', 'T1596'],
      suggestedTools: ['nmap', 'shodan', 'subfinder'],
      suggestedAgents: ['recon-specialist'],
    },
    {
      order: 2,
      tacticId: 'TA0001',
      label: 'Initial Access (IT Network)',
      description: 'Gain initial foothold in the IT network via spearphishing, exploitation of public-facing applications, or supply-chain compromise.',
      techniques: ['T1566.001', 'T1190', 'T1195.002', 'T1133'],
      suggestedTools: ['nuclei', 'gophish'],
      suggestedAgents: ['exploit-specialist', 'web-testing-specialist'],
    },
    {
      order: 3,
      tacticId: 'TA0002',
      label: 'Execution',
      description: 'Deploy and execute custom malware, PowerShell scripts, and service-based execution methods.',
      techniques: ['T1059.001', 'T1059.003', 'T1053.005', 'T1569.002'],
      suggestedTools: ['crackmapexec', 'evil-winrm'],
      suggestedAgents: ['exploit-specialist'],
    },
    {
      order: 4,
      tacticId: 'TA0004',
      label: 'Privilege Escalation',
      description: 'Escalate to domain admin through exploitation, process injection, and credential abuse.',
      techniques: ['T1068', 'T1055', 'T1547.001'],
      suggestedTools: ['crackmapexec', 'mimikatz'],
      suggestedAgents: ['privilege-escalation-specialist'],
    },
    {
      order: 5,
      tacticId: 'TA0006',
      label: 'Credential Access',
      description: 'Dump LSASS, extract NTDS.dit, and harvest credentials for OT-adjacent accounts.',
      techniques: ['T1003.001', 'T1003.003', 'T1552.001'],
      suggestedTools: ['crackmapexec', 'mimikatz', 'impacket'],
      suggestedAgents: ['privilege-escalation-specialist', 'ad-specialist'],
    },
    {
      order: 6,
      tacticId: 'TA0007',
      label: 'Discovery',
      description: 'Map AD structure, identify OT jump hosts, engineering workstations, and SCADA endpoints.',
      techniques: ['T1087.002', 'T1082', 'T1046', 'T1135', 'T1016', 'T1018'],
      suggestedTools: ['bloodhound', 'nmap', 'ldapsearch', 'enum4linux'],
      suggestedAgents: ['recon-specialist', 'ad-specialist', 'network-testing-specialist'],
    },
    {
      order: 7,
      tacticId: 'TA0008',
      label: 'Lateral Movement (IT → OT Boundary)',
      description: 'Cross from IT network to OT environment using harvested credentials, RDP to jump hosts, and SMB to engineering workstations.',
      techniques: ['T1021.001', 'T1021.002', 'T1550.002', 'T1570'],
      suggestedTools: ['crackmapexec', 'impacket', 'evil-winrm'],
      suggestedAgents: ['lateral-movement-specialist'],
    },
    {
      order: 8,
      tacticId: 'TA0009',
      label: 'Collection',
      description: 'Collect OT network configurations, PLC programming files, and SCADA documentation.',
      techniques: ['T1005', 'T1039', 'T1560.001'],
      suggestedTools: [],
      suggestedAgents: ['evidence-specialist'],
    },
    {
      order: 9,
      tacticId: 'TA0040',
      label: 'Impact',
      description: 'Execute destructive operations: wiper malware deployment, service disruption, data destruction, and inhibit system recovery. (SIMULATION ONLY — document what would happen)',
      techniques: ['T1485', 'T1486', 'T1489', 'T1490', 'T1491'],
      suggestedTools: [],
      suggestedAgents: ['reporting-specialist'],
    },
  ],
}

// ═══════════════════════════════════════════════════════════════════════════
// FINANCIAL SECTOR CHAINS
// ═══════════════════════════════════════════════════════════════════════════

export const APT38_FINANCE_CHAIN: AptAttackChain = {
  aptGroupId: 'apt38',
  name: 'APT38 — Financial Institution SWIFT Heist',
  description:
    'Models APT38\'s approach to financial institution compromise: long dwell-time reconnaissance, SWIFT network access, fraudulent transaction staging, and evidence destruction. Based on Bangladesh Bank heist and related campaigns.',
  relevantIndustries: ['financial-services'],
  recommendedImpact: 'intrusive',
  phases: [
    {
      order: 1,
      tacticId: 'TA0043',
      label: 'Reconnaissance',
      description: 'Identify bank personnel, SWIFT operators, and internal network structure. Research the target\'s financial messaging infrastructure.',
      techniques: ['T1589.002', 'T1591', 'T1593'],
      suggestedTools: ['theHarvester', 'amass', 'holehe'],
      suggestedAgents: ['recon-specialist'],
    },
    {
      order: 2,
      tacticId: 'TA0001',
      label: 'Initial Access',
      description: 'Deliver spearphishing attachments targeting bank employees. Alternatively, exploit public-facing banking web applications.',
      techniques: ['T1566.001', 'T1566.002', 'T1190'],
      suggestedTools: ['gophish', 'nuclei'],
      suggestedAgents: ['web-testing-specialist', 'exploit-specialist'],
    },
    {
      order: 3,
      tacticId: 'TA0002',
      label: 'Execution',
      description: 'Execute backdoors via macro documents, PowerShell, and service execution.',
      techniques: ['T1059.001', 'T1059.003', 'T1059.005', 'T1204.002', 'T1569.002'],
      suggestedTools: ['crackmapexec', 'evil-winrm'],
      suggestedAgents: ['exploit-specialist'],
    },
    {
      order: 4,
      tacticId: 'TA0003',
      label: 'Persistence',
      description: 'Establish persistent access through registry run keys, scheduled tasks, and Windows services.',
      techniques: ['T1547.001', 'T1053.005', 'T1543.003'],
      suggestedTools: ['crackmapexec'],
      suggestedAgents: ['privilege-escalation-specialist'],
    },
    {
      order: 5,
      tacticId: 'TA0006',
      label: 'Credential Access',
      description: 'Dump credentials from LSASS, harvest from files, and extract from credential stores to access SWIFT terminals.',
      techniques: ['T1003.001', 'T1552.001', 'T1555'],
      suggestedTools: ['crackmapexec', 'mimikatz'],
      suggestedAgents: ['privilege-escalation-specialist'],
    },
    {
      order: 6,
      tacticId: 'TA0007',
      label: 'Discovery',
      description: 'Map internal network to locate SWIFT Alliance Lite2 terminals, payment processing servers, and core banking systems.',
      techniques: ['T1082', 'T1083', 'T1046', 'T1016', 'T1049'],
      suggestedTools: ['nmap', 'enum4linux', 'ldapsearch'],
      suggestedAgents: ['recon-specialist', 'network-testing-specialist'],
    },
    {
      order: 7,
      tacticId: 'TA0008',
      label: 'Lateral Movement',
      description: 'Move laterally to reach SWIFT operator workstations and payment processing infrastructure.',
      techniques: ['T1021.001', 'T1021.002', 'T1570'],
      suggestedTools: ['crackmapexec', 'impacket'],
      suggestedAgents: ['lateral-movement-specialist'],
    },
    {
      order: 8,
      tacticId: 'TA0009',
      label: 'Collection',
      description: 'Study SWIFT message formats, capture credentials for SWIFT terminals, and collect transaction records.',
      techniques: ['T1005', 'T1560.001', 'T1119'],
      suggestedTools: [],
      suggestedAgents: ['evidence-specialist'],
    },
    {
      order: 9,
      tacticId: 'TA0040',
      label: 'Impact (Financial Theft)',
      description: 'Execute fraudulent SWIFT transactions and attempt to cover tracks. (SIMULATION ONLY — document the attack path, do not execute real transactions)',
      techniques: ['T1657'],
      suggestedTools: [],
      suggestedAgents: ['reporting-specialist'],
    },
    {
      order: 10,
      tacticId: 'TA0040',
      label: 'Impact (Evidence Destruction)',
      description: 'Deploy wiper malware to destroy evidence of the intrusion and hinder forensic investigation.',
      techniques: ['T1485', 'T1489', 'T1490'],
      suggestedTools: [],
      suggestedAgents: ['reporting-specialist'],
    },
  ],
}

export const SCATTERED_SPIDER_FINANCE_CHAIN: AptAttackChain = {
  aptGroupId: 'scattered-spider',
  name: 'Scattered Spider — Identity-Centric Cloud Compromise',
  description:
    'Models Scattered Spider\'s social-engineering-heavy approach: SIM swapping, MFA fatigue, helpdesk social engineering, and identity-provider compromise to access cloud/SaaS platforms.',
  relevantIndustries: ['financial-services', 'technology', 'telecommunications', 'retail'],
  recommendedImpact: 'intrusive',
  phases: [
    {
      order: 1,
      tacticId: 'TA0043',
      label: 'Reconnaissance',
      description: 'Identify helpdesk procedures, employee social media, and MFA implementation details. Research identity provider configuration.',
      techniques: ['T1589', 'T1589.002', 'T1591', 'T1593'],
      suggestedTools: ['theHarvester', 'holehe', 'GHunt'],
      suggestedAgents: ['recon-specialist'],
    },
    {
      order: 2,
      tacticId: 'TA0001',
      label: 'Initial Access',
      description: 'Social-engineer helpdesk for password reset, conduct SIM swap for MFA bypass, or deliver phishing links via SMS/messaging. Abuse trusted relationships through MSP portals.',
      techniques: ['T1566.002', 'T1566.003', 'T1078.004', 'T1199'],
      suggestedTools: ['gophish'],
      suggestedAgents: ['web-testing-specialist'],
    },
    {
      order: 3,
      tacticId: 'TA0006',
      label: 'Credential Access',
      description: 'Steal OAuth/SAML tokens, conduct MFA fatigue attacks (push bombing), harvest session cookies, and intercept authentication flows.',
      techniques: ['T1528', 'T1539', 'T1621', 'T1110.003', 'T1557'],
      suggestedTools: ['hydra', 'responder'],
      suggestedAgents: ['privilege-escalation-specialist'],
    },
    {
      order: 4,
      tacticId: 'TA0003',
      label: 'Persistence',
      description: 'Register new cloud credentials, add additional MFA devices, create cloud admin accounts.',
      techniques: ['T1136.003', 'T1098.001', 'T1078.004'],
      suggestedTools: [],
      suggestedAgents: ['privilege-escalation-specialist'],
    },
    {
      order: 5,
      tacticId: 'TA0005',
      label: 'Defense Evasion',
      description: 'Use stolen application tokens to bypass MFA, disable security alerting, and impersonate legitimate admins.',
      techniques: ['T1550.001', 'T1562.001'],
      suggestedTools: [],
      suggestedAgents: ['exploit-specialist'],
    },
    {
      order: 6,
      tacticId: 'TA0007',
      label: 'Discovery',
      description: 'Enumerate cloud infrastructure, identify high-value data stores, discover federated identity configurations.',
      techniques: ['T1082', 'T1087.002', 'T1580', 'T1069.002'],
      suggestedTools: [],
      suggestedAgents: ['recon-specialist'],
    },
    {
      order: 7,
      tacticId: 'TA0009',
      label: 'Collection',
      description: 'Access cloud storage, download data from SaaS platforms, collect email from cloud mailboxes, and extract data from information repositories.',
      techniques: ['T1530', 'T1213', 'T1114.002'],
      suggestedTools: [],
      suggestedAgents: ['evidence-specialist'],
    },
    {
      order: 8,
      tacticId: 'TA0010',
      label: 'Exfiltration',
      description: 'Exfiltrate data to attacker-controlled cloud storage or transfer between cloud accounts.',
      techniques: ['T1567.002', 'T1537'],
      suggestedTools: [],
      suggestedAgents: ['evidence-specialist', 'reporting-specialist'],
    },
    {
      order: 9,
      tacticId: 'TA0040',
      label: 'Impact',
      description: 'Deploy ransomware for extortion, remove account access, or threaten data exposure. (SIMULATION ONLY)',
      techniques: ['T1486', 'T1531'],
      suggestedTools: [],
      suggestedAgents: ['reporting-specialist'],
    },
  ],
}

// ═══════════════════════════════════════════════════════════════════════════
// TELECOM CHAINS
// ═══════════════════════════════════════════════════════════════════════════

export const SALT_TYPHOON_TELECOM_CHAIN: AptAttackChain = {
  aptGroupId: 'salt-typhoon',
  name: 'Salt Typhoon — Telecom Infrastructure Espionage',
  description:
    'Models Salt Typhoon\'s approach to compromising telecom infrastructure: targeting network appliances, establishing persistent access to core network systems, and harvesting call metadata and communications data.',
  relevantIndustries: ['telecommunications', 'government'],
  recommendedImpact: 'intrusive',
  phases: [
    {
      order: 1,
      tacticId: 'TA0043',
      label: 'Reconnaissance',
      description: 'Identify telecom provider infrastructure, network management systems, and internet-facing network appliances.',
      techniques: ['T1595.001', 'T1595.002', 'T1590', 'T1596'],
      suggestedTools: ['nmap', 'shodan', 'subfinder', 'nuclei'],
      suggestedAgents: ['recon-specialist'],
    },
    {
      order: 2,
      tacticId: 'TA0001',
      label: 'Initial Access',
      description: 'Exploit public-facing network appliances and telecom management interfaces. Abuse external remote services with compromised credentials.',
      techniques: ['T1190', 'T1133', 'T1078'],
      suggestedTools: ['nuclei', 'nmap', 'httpx'],
      suggestedAgents: ['exploit-specialist', 'network-testing-specialist'],
    },
    {
      order: 3,
      tacticId: 'TA0002',
      label: 'Execution',
      description: 'Execute commands through compromised network appliance CLIs and management interfaces.',
      techniques: ['T1059.001', 'T1059.003'],
      suggestedTools: ['crackmapexec'],
      suggestedAgents: ['exploit-specialist'],
    },
    {
      order: 4,
      tacticId: 'TA0003',
      label: 'Persistence',
      description: 'Install web shells on management interfaces, modify network device configurations for persistent access.',
      techniques: ['T1505.003', 'T1543.003', 'T1547.001'],
      suggestedTools: [],
      suggestedAgents: ['privilege-escalation-specialist'],
    },
    {
      order: 5,
      tacticId: 'TA0006',
      label: 'Credential Access',
      description: 'Extract credentials from network device configurations and management databases.',
      techniques: ['T1003.001', 'T1552.001'],
      suggestedTools: ['crackmapexec'],
      suggestedAgents: ['privilege-escalation-specialist'],
    },
    {
      order: 6,
      tacticId: 'TA0007',
      label: 'Discovery',
      description: 'Map the telecom core network — identify CDR databases, lawful-intercept systems, subscriber management, and interconnection points.',
      techniques: ['T1082', 'T1046', 'T1016', 'T1087.002'],
      suggestedTools: ['nmap', 'enum4linux'],
      suggestedAgents: ['recon-specialist', 'network-testing-specialist'],
    },
    {
      order: 7,
      tacticId: 'TA0008',
      label: 'Lateral Movement',
      description: 'Pivot through the telecom network from management plane to data plane and interconnection systems.',
      techniques: ['T1021.001', 'T1021.004', 'T1570'],
      suggestedTools: ['crackmapexec', 'impacket'],
      suggestedAgents: ['lateral-movement-specialist'],
    },
    {
      order: 8,
      tacticId: 'TA0009',
      label: 'Collection',
      description: 'Harvest call detail records, intercept communications data, and collect subscriber information at scale.',
      techniques: ['T1005', 'T1560.001', 'T1119'],
      suggestedTools: [],
      suggestedAgents: ['evidence-specialist'],
    },
    {
      order: 9,
      tacticId: 'TA0010',
      label: 'Exfiltration',
      description: 'Exfiltrate collected telecommunications data over encrypted channels.',
      techniques: ['T1041'],
      suggestedTools: [],
      suggestedAgents: ['evidence-specialist', 'reporting-specialist'],
    },
  ],
}

// ═══════════════════════════════════════════════════════════════════════════
// TECHNOLOGY / CLOUD CHAINS
// ═══════════════════════════════════════════════════════════════════════════

export const SILK_TYPHOON_SUPPLY_CHAIN: AptAttackChain = {
  aptGroupId: 'silk-typhoon',
  name: 'Silk Typhoon — IT Supply Chain & Cloud Exploitation',
  description:
    'Models Silk Typhoon\'s approach: mass exploitation of zero-day vulnerabilities in internet-facing applications (Exchange, remote management tools), followed by web shell deployment, credential theft, and cloud data exfiltration.',
  relevantIndustries: ['technology', 'healthcare', 'education', 'legal', 'government'],
  recommendedImpact: 'intrusive',
  phases: [
    {
      order: 1,
      tacticId: 'TA0043',
      label: 'Reconnaissance',
      description: 'Identify internet-facing Exchange servers, remote management tools, and cloud infrastructure. Scan for known vulnerable versions.',
      techniques: ['T1595.002', 'T1590', 'T1596'],
      suggestedTools: ['nuclei', 'shodan', 'subfinder', 'httpx'],
      suggestedAgents: ['recon-specialist'],
    },
    {
      order: 2,
      tacticId: 'TA0001',
      label: 'Initial Access',
      description: 'Exploit zero-day vulnerabilities in public-facing applications. Chain multiple vulnerabilities for authentication bypass and remote code execution. Alternatively, compromise IT supply-chain providers.',
      techniques: ['T1190', 'T1195.002', 'T1199', 'T1078.004'],
      suggestedTools: ['nuclei', 'httpx'],
      suggestedAgents: ['exploit-specialist', 'web-testing-specialist'],
    },
    {
      order: 3,
      tacticId: 'TA0002',
      label: 'Execution',
      description: 'Execute commands through web shells deployed on compromised servers.',
      techniques: ['T1059.001', 'T1059.003'],
      suggestedTools: ['crackmapexec'],
      suggestedAgents: ['exploit-specialist'],
    },
    {
      order: 4,
      tacticId: 'TA0003',
      label: 'Persistence',
      description: 'Deploy web shells on compromised servers. Create cloud accounts and add additional cloud credentials.',
      techniques: ['T1505.003', 'T1136.003', 'T1098.001'],
      suggestedTools: [],
      suggestedAgents: ['privilege-escalation-specialist'],
    },
    {
      order: 5,
      tacticId: 'TA0006',
      label: 'Credential Access',
      description: 'Dump credentials from compromised servers, steal application access tokens, and extract secrets from cloud vaults.',
      techniques: ['T1003.001', 'T1528', 'T1552.001'],
      suggestedTools: ['crackmapexec', 'mimikatz'],
      suggestedAgents: ['privilege-escalation-specialist'],
    },
    {
      order: 6,
      tacticId: 'TA0007',
      label: 'Discovery',
      description: 'Enumerate cloud tenants, discover connected services, identify high-value data repositories.',
      techniques: ['T1082', 'T1087.002', 'T1083', 'T1046', 'T1580'],
      suggestedTools: ['nmap', 'ldapsearch'],
      suggestedAgents: ['recon-specialist'],
    },
    {
      order: 7,
      tacticId: 'TA0008',
      label: 'Lateral Movement',
      description: 'Pivot from compromised on-prem servers to cloud infrastructure using stolen tokens and credentials.',
      techniques: ['T1021.002', 'T1550.001'],
      suggestedTools: ['crackmapexec', 'impacket'],
      suggestedAgents: ['lateral-movement-specialist'],
    },
    {
      order: 8,
      tacticId: 'TA0009',
      label: 'Collection',
      description: 'Access email mailboxes, download documents from cloud storage, and collect data from information repositories.',
      techniques: ['T1005', 'T1114.002', 'T1530', 'T1213'],
      suggestedTools: [],
      suggestedAgents: ['evidence-specialist'],
    },
    {
      order: 9,
      tacticId: 'TA0010',
      label: 'Exfiltration',
      description: 'Exfiltrate data over C2 channel or to attacker-controlled cloud storage.',
      techniques: ['T1041', 'T1567.002'],
      suggestedTools: [],
      suggestedAgents: ['evidence-specialist', 'reporting-specialist'],
    },
  ],
}

// ═══════════════════════════════════════════════════════════════════════════
// HEALTHCARE CHAIN
// ═══════════════════════════════════════════════════════════════════════════

export const LAZARUS_HEALTHCARE_CHAIN: AptAttackChain = {
  aptGroupId: 'lazarus',
  name: 'Lazarus — Healthcare Ransomware & Espionage',
  description:
    'Models the Lazarus umbrella\'s approach to healthcare targeting: combining espionage objectives (vaccine/drug research theft) with ransomware revenue generation. Based on CISA advisories on Maui ransomware and related campaigns.',
  relevantIndustries: ['healthcare', 'financial-services'],
  recommendedImpact: 'intrusive',
  phases: [
    {
      order: 1,
      tacticId: 'TA0043',
      label: 'Reconnaissance',
      description: 'Identify healthcare IT infrastructure, research staff, and internet-facing systems including VPN and web portals.',
      techniques: ['T1589.002', 'T1590', 'T1594', 'T1595.002'],
      suggestedTools: ['theHarvester', 'subfinder', 'nuclei', 'shodan'],
      suggestedAgents: ['recon-specialist'],
    },
    {
      order: 2,
      tacticId: 'TA0001',
      label: 'Initial Access',
      description: 'Exploit public-facing healthcare web applications, deliver spearphishing to research staff, or abuse supply-chain trust.',
      techniques: ['T1190', 'T1566.001', 'T1566.002', 'T1195.002'],
      suggestedTools: ['nuclei', 'gophish'],
      suggestedAgents: ['exploit-specialist', 'web-testing-specialist'],
    },
    {
      order: 3,
      tacticId: 'TA0002',
      label: 'Execution',
      description: 'Deploy custom malware through multiple scripting interpreters and exploits.',
      techniques: ['T1059.001', 'T1059.003', 'T1059.006', 'T1204.002', 'T1203'],
      suggestedTools: ['crackmapexec', 'evil-winrm'],
      suggestedAgents: ['exploit-specialist'],
    },
    {
      order: 4,
      tacticId: 'TA0003',
      label: 'Persistence',
      description: 'Establish persistence via registry keys, scheduled tasks, services, and DLL hijacking.',
      techniques: ['T1547.001', 'T1053.005', 'T1543.003', 'T1574.001'],
      suggestedTools: ['crackmapexec'],
      suggestedAgents: ['privilege-escalation-specialist'],
    },
    {
      order: 5,
      tacticId: 'TA0004',
      label: 'Privilege Escalation',
      description: 'Escalate privileges through exploitation, process injection, and token manipulation.',
      techniques: ['T1068', 'T1055', 'T1134'],
      suggestedTools: ['crackmapexec'],
      suggestedAgents: ['privilege-escalation-specialist'],
    },
    {
      order: 6,
      tacticId: 'TA0006',
      label: 'Credential Access',
      description: 'Dump credentials from LSASS, extract from files and credential stores.',
      techniques: ['T1003.001', 'T1552.001', 'T1555'],
      suggestedTools: ['crackmapexec', 'mimikatz'],
      suggestedAgents: ['privilege-escalation-specialist'],
    },
    {
      order: 7,
      tacticId: 'TA0007',
      label: 'Discovery',
      description: 'Identify EHR systems, research databases, file servers with clinical trial data, and network shares.',
      techniques: ['T1082', 'T1083', 'T1087.002', 'T1046', 'T1016'],
      suggestedTools: ['nmap', 'ldapsearch', 'enum4linux'],
      suggestedAgents: ['recon-specialist', 'network-testing-specialist'],
    },
    {
      order: 8,
      tacticId: 'TA0008',
      label: 'Lateral Movement',
      description: 'Move to research servers, EHR systems, and file shares containing clinical data.',
      techniques: ['T1021.001', 'T1021.002', 'T1550.002', 'T1570'],
      suggestedTools: ['crackmapexec', 'impacket', 'evil-winrm'],
      suggestedAgents: ['lateral-movement-specialist'],
    },
    {
      order: 9,
      tacticId: 'TA0009',
      label: 'Collection',
      description: 'Collect clinical trial data, drug research, patient records, and financial data.',
      techniques: ['T1560.001', 'T1005', 'T1119'],
      suggestedTools: [],
      suggestedAgents: ['evidence-specialist'],
    },
    {
      order: 10,
      tacticId: 'TA0010',
      label: 'Exfiltration',
      description: 'Exfiltrate research data and financial records over encrypted channels.',
      techniques: ['T1041', 'T1048'],
      suggestedTools: [],
      suggestedAgents: ['evidence-specialist'],
    },
    {
      order: 11,
      tacticId: 'TA0040',
      label: 'Impact',
      description: 'Deploy ransomware for revenue generation, destroy evidence, and inhibit system recovery. (SIMULATION ONLY)',
      techniques: ['T1486', 'T1485', 'T1489', 'T1490'],
      suggestedTools: [],
      suggestedAgents: ['reporting-specialist'],
    },
  ],
}

// ═══════════════════════════════════════════════════════════════════════════
// MANUFACTURING CHAIN
// ═══════════════════════════════════════════════════════════════════════════

export const APT41_MANUFACTURING_CHAIN: AptAttackChain = {
  aptGroupId: 'apt41',
  name: 'APT41 — Manufacturing IP Theft & Espionage',
  description:
    'Models APT41\'s dual-mission approach in manufacturing environments: supply-chain compromise for initial access, extensive AD exploitation for lateral movement, and targeted theft of engineering data and trade secrets.',
  relevantIndustries: ['manufacturing', 'technology', 'healthcare'],
  recommendedImpact: 'intrusive',
  phases: [
    {
      order: 1,
      tacticId: 'TA0043',
      label: 'Reconnaissance',
      description: 'Identify target manufacturing infrastructure, software supply chain, engineering portals, and key technical personnel.',
      techniques: ['T1589.002', 'T1590', 'T1593', 'T1594'],
      suggestedTools: ['theHarvester', 'subfinder', 'amass', 'shodan'],
      suggestedAgents: ['recon-specialist'],
    },
    {
      order: 2,
      tacticId: 'TA0001',
      label: 'Initial Access',
      description: 'Compromise software supply chain, exploit public-facing applications, or leverage trusted relationships with vendors.',
      techniques: ['T1195.002', 'T1190', 'T1199', 'T1566.001'],
      suggestedTools: ['nuclei', 'httpx', 'gophish'],
      suggestedAgents: ['exploit-specialist', 'web-testing-specialist'],
    },
    {
      order: 3,
      tacticId: 'TA0002',
      label: 'Execution',
      description: 'Execute through PowerShell, WMI, scheduled tasks, and custom tooling.',
      techniques: ['T1059.001', 'T1059.003', 'T1053.005', 'T1047'],
      suggestedTools: ['crackmapexec', 'evil-winrm'],
      suggestedAgents: ['exploit-specialist'],
    },
    {
      order: 4,
      tacticId: 'TA0003',
      label: 'Persistence',
      description: 'Deploy web shells, create services, establish registry persistence, and manipulate accounts.',
      techniques: ['T1505.003', 'T1543.003', 'T1547.001', 'T1098'],
      suggestedTools: ['crackmapexec'],
      suggestedAgents: ['privilege-escalation-specialist'],
    },
    {
      order: 5,
      tacticId: 'TA0004',
      label: 'Privilege Escalation',
      description: 'Exploit local vulnerabilities, inject processes, and manipulate access tokens to escalate.',
      techniques: ['T1068', 'T1055', 'T1134'],
      suggestedTools: ['crackmapexec'],
      suggestedAgents: ['privilege-escalation-specialist'],
    },
    {
      order: 6,
      tacticId: 'TA0006',
      label: 'Credential Access',
      description: 'Dump LSASS and NTDS.dit, Kerberoast service accounts, and harvest credentials from files.',
      techniques: ['T1003.001', 'T1003.003', 'T1558.003', 'T1552.001'],
      suggestedTools: ['crackmapexec', 'mimikatz', 'impacket'],
      suggestedAgents: ['privilege-escalation-specialist', 'ad-specialist'],
    },
    {
      order: 7,
      tacticId: 'TA0007',
      label: 'Discovery',
      description: 'Map AD structure, identify engineering file shares, CAD/CAM servers, and manufacturing databases.',
      techniques: ['T1087.002', 'T1082', 'T1083', 'T1046', 'T1135', 'T1069.002', 'T1482'],
      suggestedTools: ['bloodhound', 'nmap', 'ldapsearch', 'enum4linux'],
      suggestedAgents: ['recon-specialist', 'ad-specialist'],
    },
    {
      order: 8,
      tacticId: 'TA0008',
      label: 'Lateral Movement',
      description: 'Pivot to engineering workstations and file servers using harvested credentials and pass-the-hash.',
      techniques: ['T1021.001', 'T1021.002', 'T1550.002', 'T1570'],
      suggestedTools: ['crackmapexec', 'impacket', 'evil-winrm'],
      suggestedAgents: ['lateral-movement-specialist'],
    },
    {
      order: 9,
      tacticId: 'TA0009',
      label: 'Collection',
      description: 'Collect engineering designs, manufacturing process data, trade secrets, and corporate strategy documents.',
      techniques: ['T1560.001', 'T1005', 'T1039', 'T1213'],
      suggestedTools: [],
      suggestedAgents: ['evidence-specialist'],
    },
    {
      order: 10,
      tacticId: 'TA0010',
      label: 'Exfiltration',
      description: 'Exfiltrate collected IP over encrypted channels or to cloud storage.',
      techniques: ['T1041', 'T1567.002'],
      suggestedTools: [],
      suggestedAgents: ['evidence-specialist', 'reporting-specialist'],
    },
  ],
}

// ═══════════════════════════════════════════════════════════════════════════
// MASTER REGISTRY
// ═══════════════════════════════════════════════════════════════════════════

export const ATTACK_CHAINS: AptAttackChain[] = [
  APT29_GOV_CHAIN,
  APT28_GOV_CHAIN,
  VOLT_TYPHOON_INFRA_CHAIN,
  SANDWORM_ICS_CHAIN,
  APT38_FINANCE_CHAIN,
  SCATTERED_SPIDER_FINANCE_CHAIN,
  SALT_TYPHOON_TELECOM_CHAIN,
  SILK_TYPHOON_SUPPLY_CHAIN,
  LAZARUS_HEALTHCARE_CHAIN,
  APT41_MANUFACTURING_CHAIN,
]

export function findAttackChain(aptGroupId: string): AptAttackChain | undefined {
  return ATTACK_CHAINS.find(c => c.aptGroupId === aptGroupId)
}

export function findAttackChainsByIndustry(sector: AptAttackChain['relevantIndustries'][number]): AptAttackChain[] {
  return ATTACK_CHAINS.filter(c => c.relevantIndustries.includes(sector))
}

export function getAttackChainForSimulation(
  aptGroupId: string,
  industry: AptAttackChain['relevantIndustries'][number],
): AptAttackChain | undefined {
  return ATTACK_CHAINS.find(
    c => c.aptGroupId === aptGroupId && c.relevantIndustries.includes(industry),
  ) ?? ATTACK_CHAINS.find(c => c.aptGroupId === aptGroupId)
}
